name: CMake GTest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure with CMake
      run: cmake --preset msvc-debug

    - name: Build
      run: cmake --build --preset msvc-debug-build --target NeuralNetworkTest

    - name: Run GTest
      shell: pwsh
      run: |
        build/msvc-debug/neural-network/tests/Debug/NeuralNetworkTest.exe
        exit $LASTEXITCODE
