name: ubuntu-x86_64

on:
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.cpp'
      - '**.cmake'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  pull_request:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.cpp'
      - '**.cmake'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  workflow_dispatch:

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "MinGW x86_64"
            preset: "mingw-debug"
            cuda: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/setup-nasm@v1

    - name: Configure and Build
      shell: bash
      run: |
        cmake --preset ${{ matrix.preset }}
        cmake --build --preset ${{ matrix.preset }}-build

    - name: Run
      shell: bash
      run: |
        build/${{ matrix.preset }}/neural-network/tests/NeuralNetworkTest