name: ubuntu-x86_64

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "MinGW x86_64"
            preset: "mingw-debug"
            cuda: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/setup-nasm@v1

    - name: Install latest GCC and G++
      run: |
        sudo apt-get install -y gcc-15 g++-15
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 100

    - name: Configure and Build
      shell: bash
      run: |
        cmake --preset ${{ matrix.preset }}
        cmake --build --preset ${{ matrix.preset }}-build

    - name: Run
      shell: bash
      run: |
        build/${{ matrix.preset }}/neural-network/tests/NeuralNetworkTest