name: windows-arm64

on:
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.cpp'
      - '**.cmake'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  pull_request:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.cpp'
      - '**.cmake'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  workflow_dispatch:

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "MSVC arm64"
            preset: "msvc-debug-arm64"
            setup_action: "msvc"
            cuda: false

    runs-on: windows-11-arm

    steps:
    - uses: actions/checkout@v4

    - name: Setup CUDA
      if: matrix.cuda
      uses: Jimver/cuda-toolkit@v0.2.23
      with:
        cuda: '12.8.1'
        method: 'network'
        use-github-cache: false

    - name: Setup MSVC
      if: matrix.setup_action == 'msvc'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup MSYS2
      if: matrix.setup_action == 'msys2'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-nasm
          git
        msystem: MINGW64

    - name: Configure and Build with MSVC
      if: matrix.setup_action == 'msvc'
      shell: pwsh
      run: |
        cmake --preset ${{ matrix.preset }}
        cmake --build --preset ${{ matrix.preset }}-build

    - name: Configure and Build with MinGW
      if: matrix.setup_action == 'msys2'
      shell: msys2 {0}
      run: |
        cmake --preset ${{ matrix.preset }}
        cmake --build --preset ${{ matrix.preset }}-build

    - name: Run with MSVC
      if: matrix.setup_action == 'msvc' && !matrix.cuda
      shell: pwsh
      run: |
        build/${{ matrix.preset }}/neural-network/tests/Debug/NeuralNetworkTest.exe

    - name: Run with MinGW
      if: matrix.setup_action == 'msys2'
      shell: msys2 {0}
      run: |
        build/${{ matrix.preset }}/neural-network/tests/NeuralNetworkTest.exe